- name: Cluster uprava zoo.cfg 
  hosts: nodes
  become: yes

  tasks:
    - name: Ziskani IP adres z nodes
      set_fact:
        ip1: "{{ hostvars[groups['nodes'][0]]['ansible_default_ipv4']['address'] }}"
        ip2: "{{ hostvars[groups['nodes'][1]]['ansible_default_ipv4']['address'] }}"
        ip3: "{{ hostvars[groups['nodes'][2]]['ansible_default_ipv4']['address'] }}"
        ip4: "{{ hostvars[groups['nodes'][3]]['ansible_default_ipv4']['address'] }}"
        ip5: "{{ hostvars[groups['nodes'][4]]['ansible_default_ipv4']['address'] }}"

    - name: Pridani konfigurace do zoo.cfg
      blockinfile:
        path: /opt/zookeeper/conf/zoo.cfg
        block: |
          initLimit=10
          syncLimit=5
          server.1={{ ip1 }}:2888:3888
          server.2={{ ip2 }}:2888:3888
          server.3={{ ip3 }}:2888:3888

    - name: Restart zk.service
      systemd:
        name: zk.service
        state: restarted
