---
- name: Instalace a konfigurace Nginx serveru
  hosts: webserver
  become: yes

  tasks:
    - name: Instalace Nginx
      apt:
        name: nginx
        state: present
      tags: nginx_install

    - name: Konfigurace Nginx pro ngx_http_stub_status_module
      copy:
        src: files/nginx_stub_status.conf
        dest: /etc/nginx/sites-available/nginx_stub_status.conf
      tags: nginx_configure
 
    - name: Symlink
      file:
        src: /etc/nginx/sites-available/nginx_stub_status.conf
        dest: /etc/nginx/sites-enabled/nginx_stub_status.conf
        state: link
      notify: Restart Nginx
      tags: nginx_configure

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

